
INSERT INTO sec_roles (ROLE_NAME) VALUES ('ROLE_BUYER');
INSERT INTO sec_roles (ROLE_NAME) VALUES ('ROLE_SELLER');
INSERT INTO sec_roles (ROLE_NAME) VALUES ('ROLE_ADMIN');

insert into CATEGORY  (CAT_NAME) VALUES ('VEGETABLES');
insert into CATEGORY  (CAT_NAME) VALUES ('FRUITS'); 


insert into user (CONTACT_NO,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) VALUES ('9653265623','shubhamkognole@gmail.com','Shubham','Kognole','12345');
insert into user (CONTACT_NO,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) VALUES ('6598875133','bhaveshrathod@gmail.com','Bhavesh','Rathod','12345');
insert into user (CONTACT_NO,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD) VALUES ('6356874523','karannigvekar@gmail.com','Karan','Nigvekar','12345');



insert into PRODUCTS  (PRICE,PROD_NAME,QUANTITY,CAT_ID,IS_ACTIVE) VALUES (62,'CUCUMBER',1,1,0);
insert into PRODUCTS  (PRICE,PROD_NAME,QUANTITY,CAT_ID,IS_ACTIVE) VALUES (36,'ONION',1,1,0);
insert into PRODUCTS  (PRICE,PROD_NAME,QUANTITY,CAT_ID,IS_ACTIVE) VALUES (30,'TOMATO',1,1,0);






